waypoint: [
  [0, 0, 0, 0],
  [1.5, 1.5, 0, 45],
  [2, 0, 0, 0],
  [1.5, -1.5, 0, -45],
  [0, 0, 0, 0]
]

# waypoint: [
#   [0, 0, 0, 0],
#   [0, 2, 0, 90],
#   [1.5, 1.5, 0, 45],
#   [2, 0, 0, 0],
#   [1.5, -1.5, 0, -45],
#   [0, -2, 0, -90],
#   [0, 0, 0, 0]
# ]
